export const LIST_ALL_PARTICIPANTS = "LIST_ALL_PARTICIPANTS";
export const GET_USER_INFO = "GET_USER_INFO";
export const LIST_ALL_MESSAGES = "LIST_ALL_MESSAGES";
export const LIST_ALL_ADD_FRIEND_REQUEST_RECEIVED = "LIST_ALL_ADD_FRIEND_RECEIVED";
export const LIST_ALL_CHATS = "LIST_ALL_CHATS";
